### ISSUE TITLE
Provide findjsoncpp.cmake with conda package

### ISSUE THREAD

**Issue by ManifoldFR** [conda-forge/jsoncpp-feedstock#25]
The jsoncpp package normally provides the a cmake configuration file `jsoncppConfig.cmake` (https://github.com/open-source-parsers/jsoncpp/issues/927) which allows to find the include and library files in a CMake project.

Unfortunately this is missing when installing the conda package. Normally we could find that file in `$CONDA_PREFIX/lib/cmake/`, but it is not the case. We can find it when installing `libsjoncpp-dev` using `apt`, at the location `/usr/lib/x86_64-linux-gnu/cmake/jsoncpp` on Ubuntu.

**Comment by jakirkham** [comment]
Would raise this with upstream. This should be handled as part of the install step in their `CMakeLists.txt`

**Comment by ManifoldFR** [comment]
Ok, I'll bring this up with upstream. I figured it was something with how
the install script was called, didn't think it'd be the script itself

**Comment by jakirkham** [comment]
We're also publishing the latest version. So might be worth checking if things got fixed by upstream since this was raised

**Comment by jakirkham** [comment]
Am seeing this in [the logs]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=402656&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=3448 ):

```
-- Installing: $PREFIX/lib/cmake/jsoncpp/jsoncppConfig.cmake
```

There are a few other CMake files getting copied over. So maybe this is already solved.

That said, would be good to add a test to the package. Happy to accept a PR if you are up to it 🙂

**Comment by timsnyder** [comment]
It's definitely in the package but the permissions are jacked for some reason:
```
% pwd 
conda/pkgs/jsoncpp-1.9.5-h4bd325d_1/lib
% ls -l
total 312
drwx------ 3 spa.conda spa.conda_g   4096 Aug  3 16:28 cmake
lrwxrwxrwx 1 spa.conda spa.conda_g     19 Aug  3 16:28 libjsoncpp.so -> libjsoncpp.so.1.9.5
-rwxrwxr-x 2 spa.conda spa.conda_g 300736 Dec 30  2021 libjsoncpp.so.1.9.5
lrwxrwxrwx 1 spa.conda spa.conda_g     19 Aug  3 16:28 libjsoncpp.so.25 -> libjsoncpp.so.1.9.5
drwx------ 3 spa.conda spa.conda_g   4096 Aug  3 16:28 objects-Release
drwx------ 2 spa.conda spa.conda_g   4096 Aug  3 16:28 pkgconfig
```
The `lib/cmake`, `lib/pkgconfig` directories in the package have permissions 0x700 and that's strange.  When I install the package as one user and have another try to use it, it causes problems.  I'm going to look upstream to see why the permissions are so weird in their install.

**Comment by traversaro** [comment]
> That said, would be good to add a test to the package. Happy to accept a PR if you are up to it 🙂

I added a test in https://github.com/conda-forge/jsoncpp-feedstock/pull/39 using https://github.com/ami-iit/cmake-package-check .
