### ISSUE TITLE
CMake targets files are overwritten for shared library

### ISSUE THREAD

**Issue by johnwason** [conda-forge/jsoncpp-feedstock#30]
- [ x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The feedstock is currently building first for the shared library, and then for the static library. This is overwriting the shared cmake targets file installed to the environment with the static targets file, meaning that `jsoncpp_lib` is not defined after `find_packag` is used. The build needs to either only build for `jsoncpp_lib`, or patch the targets file so that it contains both the static and shared cmake target.

**Comment by traversaro** [comment]
For compliance with CFEP-18 (https://github.com/conda-forge/cfep/blob/master/cfep-18.md) I think we should simply remove the static builds, or if necessary add `-static` output with just the static library, i.e. quoting from CFEP-18:

> To implement the CFEP, we would remove static libraries from existing packages in new builds. Quite often static libraries were included by default without the need for them or just because they are the default output. They are in most cases not used/needed.
>
> If the static libraries are needed though, they should be added as a separate output with a -static suffix, see https://github.com/conda-forge/krb5-feedstock/pull/23/files .

@conda-forge/jsoncpp any preference?

**Comment by matthiasdiener** [comment]
FWIW, I'd prefer just shipping the shared libraries.

**Comment by johnwason** [comment]
Any progress on this issue? Do I need to create a PR?

**Comment by traversaro** [comment]
> 
> 
> Any progress on this issue? Do I need to create a PR?

I don't plant to tackle this until next week, so if you want to do a PR please go ahead, thanks!
